/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Enums.TiposDePessoaEnum;
import Utils.Planilha;
import com.formdev.flatlaf.FlatLightLaf;
import dbUtils.FornecedorDao;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Fornecedor;
import model.Usuario;

/**
 *
 * @author bssil
 */
public class CadastroDeFornecedorView extends javax.swing.JFrame {

    Usuario usuarioLogado;
    Fornecedor fornecedorAEditar;
    DefaultListModel listaTiposDePessoa = new DefaultListModel();
    DefaultListModel listaDeFornecedores = new DefaultListModel();
    DefaultTableModel tabelaDeFornecedores = new DefaultTableModel();
    DefaultComboBoxModel tipoDePessoasComboBOx =  new DefaultComboBoxModel();
    FornecedorDao fornecDao = new FornecedorDao();
    /**
     * Creates new form CadastroDeFornecedorView
     * @param usuarioLogado
     */
    public CadastroDeFornecedorView(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado= usuarioLogado;
        this.usuarioLogadoLabel.setText(usuarioLogado.getNome());
        popUpTipoPessoaFornecedor.add(panelListaTiposDepessoa);
        popUpFornecedorAEditar.add(panelListaDeFornecedores);
        usuarioLogadoLabel.setText(usuarioLogado.getNome());
        for(TiposDePessoaEnum tipo : TiposDePessoaEnum.values()){
            listaTiposDePessoa.addElement(tipo);
            tipoDePessoasComboBOx.addElement(tipo);
        }
        tabelaDeFornecedores.addColumn("ID");
        tabelaDeFornecedores.addColumn("NOME");
        tabelaDeFornecedores.addColumn("FANTASIA");
        tabelaDeFornecedores.addColumn("UF");
        tabelaDeFornecedores.addColumn("CNPJ");
        tabelaDeFornecedores.addColumn("TIPO PESSOA");
        tipoPessoaComboBox.setSelectedIndex(-1);
        buscaFornecedoresTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpTipoPessoaFornecedor = new javax.swing.JPopupMenu();
        panelListaTiposDepessoa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaTiposDePessoa = new javax.swing.JList<>();
        popUpFornecedorAEditar = new javax.swing.JPopupMenu();
        panelListaDeFornecedores = new javax.swing.JPanel();
        jScrollPaneFornec = new javax.swing.JScrollPane();
        jListaDeFornecedores = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        usuarioLogadoLabel = new javax.swing.JLabel();
        cadastroFornecedorPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        filtroTabelaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaDeFornecedores = new javax.swing.JTable();
        exportarParaPlanilhaButton = new javax.swing.JButton();
        cadastroFornecedor = new javax.swing.JPanel();
        nomeFornecedorCadastrarTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fantasiaFornecedorCadastrarTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnpjFornecedorCadastrarTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ufCadastarFornecedorTextField = new javax.swing.JTextField();
        logradouroCadastarFornecedorTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        foneCadastarFornecedorTextField = new javax.swing.JTextField();
        numeroCadastarFornecedorTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailCadastarFornecedorTextField = new javax.swing.JTextField();
        cepCadastarFornecedorTextField = new javax.swing.JTextField();
        salvarCadastroFornecedorlButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bairroCadastarFornecedorTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        municipioFornecedorFilialTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        iEFornecedorCadastrarTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tipoPessoaCadastroComboBox = new javax.swing.JComboBox<>();
        editarFornecedorPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        emailFornecedorEditarTextField = new javax.swing.JTextField();
        cepFornecedorEditarTextField = new javax.swing.JTextField();
        salvarCadastroFornecedorButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        bairroFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        municipioFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fantasiaFornecedorEditarTextField = new javax.swing.JTextField();
        iEFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cnpjFornecedorEditarTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        ufFornecedorEditarTextField = new javax.swing.JTextField();
        logradouroFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        foneFornecedorEditarTextField = new javax.swing.JTextField();
        nomeFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        numeroFornecedorEditarTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        fornecedorAPesquisarEditarTextField = new javax.swing.JTextField();
        editarFornecedorButton = new javax.swing.JButton();
        statusFornecedorButton = new javax.swing.JCheckBox();
        tipoPessoaComboBox = new javax.swing.JComboBox<>();

        popUpTipoPessoaFornecedor.setFocusable(false);

        panelListaTiposDepessoa.setRequestFocusEnabled(false);

        jListaTiposDePessoa.setModel(listaTiposDePessoa);
        jListaTiposDePessoa.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaTiposDePessoaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaTiposDePessoa);

        javax.swing.GroupLayout panelListaTiposDepessoaLayout = new javax.swing.GroupLayout(panelListaTiposDepessoa);
        panelListaTiposDepessoa.setLayout(panelListaTiposDepessoaLayout);
        panelListaTiposDepessoaLayout.setHorizontalGroup(
            panelListaTiposDepessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        panelListaTiposDepessoaLayout.setVerticalGroup(
            panelListaTiposDepessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        popUpFornecedorAEditar.setFocusable(false);

        jListaDeFornecedores.setModel(listaDeFornecedores);
        jListaDeFornecedores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaDeFornecedoresValueChanged(evt);
            }
        });
        jScrollPaneFornec.setViewportView(jListaDeFornecedores);

        javax.swing.GroupLayout panelListaDeFornecedoresLayout = new javax.swing.GroupLayout(panelListaDeFornecedores);
        panelListaDeFornecedores.setLayout(panelListaDeFornecedoresLayout);
        panelListaDeFornecedoresLayout.setHorizontalGroup(
            panelListaDeFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaDeFornecedoresLayout.createSequentialGroup()
                .addComponent(jScrollPaneFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelListaDeFornecedoresLayout.setVerticalGroup(
            panelListaDeFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneFornec, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        usuarioLogadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarioLogadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        usuarioLogadoLabel.setText("usuarioLogado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cadastroFornecedorPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cadastroFornecedorPanelStateChanged(evt);
            }
        });

        jLabel14.setText("PESQUISAR");

        filtroTabelaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        filtroTabelaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroTabelaTextFieldKeyReleased(evt);
            }
        });

        jTabelaDeFornecedores.setModel(tabelaDeFornecedores);
        jScrollPane2.setViewportView(jTabelaDeFornecedores);

        exportarParaPlanilhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sheets.png"))); // NOI18N
        exportarParaPlanilhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarParaPlanilhaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtroTabelaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportarParaPlanilhaButton)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(filtroTabelaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportarParaPlanilhaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        cadastroFornecedorPanel.addTab("Fornecedores", jPanel2);

        jLabel1.setText("NOME");

        jLabel2.setText("FANTASIA");

        jLabel3.setText("CNPJ");

        cnpjFornecedorCadastrarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("LOGRADOURO");

        jLabel10.setText("FONE");

        jLabel5.setText("NUMERO");

        jLabel11.setText("EMAIL");

        jLabel6.setText("CEP");

        salvarCadastroFornecedorlButton.setText("Salvar");
        salvarCadastroFornecedorlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCadastroFornecedorlButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("BAIRRO");

        jLabel8.setText("MUNICIPIO");

        jLabel9.setText("UF");

        jLabel12.setText("INSCRIÇÃO ESTADUAL");

        iEFornecedorCadastrarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel13.setText("TIPO PESSOA");

        tipoPessoaCadastroComboBox.setModel(tipoDePessoasComboBOx);
        tipoPessoaCadastroComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPessoaCadastroComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroFornecedorLayout = new javax.swing.GroupLayout(cadastroFornecedor);
        cadastroFornecedor.setLayout(cadastroFornecedorLayout);
        cadastroFornecedorLayout.setHorizontalGroup(
            cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fantasiaFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnpjFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iEFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipoPessoaCadastroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cepCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bairroCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioFornecedorFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 246, Short.MAX_VALUE))
                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logradouroCadastarFornecedorTextField))
                            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(salvarCadastroFornecedorlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(foneCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        cadastroFornecedorLayout.setVerticalGroup(
            cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroFornecedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantasiaFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnpjFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iEFornecedorCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoPessoaCadastroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(logradouroCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cepCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(bairroCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(municipioFornecedorFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ufCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(foneCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(emailCadastarFornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(salvarCadastroFornecedorlButton)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        cadastroFornecedorPanel.addTab("Cadastrar fornecedor", cadastroFornecedor);

        jLabel15.setText("CEP");

        salvarCadastroFornecedorButton.setText("Salvar");
        salvarCadastroFornecedorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCadastroFornecedorButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("BAIRRO");

        jLabel17.setText("MUNICIPIO");

        jLabel18.setText("UF");

        jLabel19.setText("INSCRIÇÃO ESTADUAL");

        iEFornecedorEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel20.setText("CNPJ");

        jLabel21.setText("TIPO PESSOA");

        cnpjFornecedorEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel22.setText("LOGRADOURO");

        jLabel23.setText("FONE");

        jLabel24.setText("NUMERO");

        jLabel25.setText("NOME");

        jLabel26.setText("FANTASIA");

        jLabel27.setText("EMAIL");

        jLabel28.setText("PESQUISAR");

        fornecedorAPesquisarEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fornecedorAPesquisarEditarTextField.setToolTipText("");
        fornecedorAPesquisarEditarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fornecedorAPesquisarEditarTextFieldKeyReleased(evt);
            }
        });

        editarFornecedorButton.setText("Editar");
        editarFornecedorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFornecedorButtonActionPerformed(evt);
            }
        });

        statusFornecedorButton.setText("Ativo");

        tipoPessoaComboBox.setModel(tipoDePessoasComboBOx);

        javax.swing.GroupLayout editarFornecedorPanelLayout = new javax.swing.GroupLayout(editarFornecedorPanel);
        editarFornecedorPanel.setLayout(editarFornecedorPanelLayout);
        editarFornecedorPanelLayout.setHorizontalGroup(
            editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                        .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logradouroFornecedorEditarTextField))
                            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnpjFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iEFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoPessoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarFornecedorPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salvarCadastroFornecedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addContainerGap())
                    .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fornecedorAPesquisarEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarFornecedorButton)
                        .addGap(26, 26, 26))
                    .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                        .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cepFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foneFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(municipioFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ufFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                        .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(nomeFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statusFornecedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fantasiaFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        editarFornecedorPanelLayout.setVerticalGroup(
            editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarFornecedorPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(fornecedorAPesquisarEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFornecedorButton))
                .addGap(25, 25, 25)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(nomeFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(fantasiaFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(cnpjFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21)
                        .addComponent(iEFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoPessoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarFornecedorPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addComponent(logradouroFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ufFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(numeroFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(cepFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(bairroFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(municipioFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(19, 19, 19)
                .addGroup(editarFornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(foneFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(emailFornecedorEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusFornecedorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarCadastroFornecedorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        cadastroFornecedorPanel.addTab("Editar fornecedor", editarFornecedorPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastroFornecedorPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroFornecedorPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarCadastroFornecedorlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCadastroFornecedorlButtonActionPerformed

        
        if(validaCamposCadastroFornecedor()){
            Fornecedor fornec = new Fornecedor();
            fornec.setNome(nomeFornecedorCadastrarTextField.getText());
            fornec.setFantasia(fantasiaFornecedorCadastrarTextField.getText());
            fornec.setBairro(bairroCadastarFornecedorTextField.getText());
            fornec.setMunicipio(municipioFornecedorFilialTextField.getText());
            fornec.setCep(cepCadastarFornecedorTextField.getText());
            fornec.setCnpj(cnpjFornecedorCadastrarTextField.getText());
            fornec.setNumero(numeroCadastarFornecedorTextField.getText());
            fornec.setInscricaoEstadual(iEFornecedorCadastrarTextField.getText());
            fornec.setEmail(emailCadastarFornecedorTextField.getText());
            fornec.setFone(foneCadastarFornecedorTextField.getText());
            fornec.setLogradouro(logradouroCadastarFornecedorTextField.getText());
            fornec.setUf(ufCadastarFornecedorTextField.getText());
          //  fornec.setTipoPessoa(TiposDePessoaEnum.valor(listaTiposDePessoa.getElementAt(jListaTiposDePessoa.getSelectedIndex()).toString()));
            fornec.setTipoPessoa(TiposDePessoaEnum.valor(tipoPessoaCadastroComboBox.getSelectedItem().toString()));
            FornecedorDao dao = new FornecedorDao();
            String fornecedorCadastrado = dao.cadastrarFornecedor(fornec,usuarioLogado);
            if(!fornecedorCadastrado.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Fornecedor " + fornecedorCadastrado + " - " + fornec.getNome() + " cadastrado.");
                limpaTela(cadastroFornecedor);
            }
        }
    }//GEN-LAST:event_salvarCadastroFornecedorlButtonActionPerformed

    private void jListaTiposDePessoaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaTiposDePessoaValueChanged
    
    }//GEN-LAST:event_jListaTiposDePessoaValueChanged

    private void salvarCadastroFornecedorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCadastroFornecedorButtonActionPerformed
       if(fornecedorAEditar != null){
         editarFornecedor();
         JOptionPane.showMessageDialog(rootPane,  fornecDao.editarFornecedor(fornecedorAEditar, usuarioLogado));
           limpaTela(editarFornecedorPanel);
       }
    }//GEN-LAST:event_salvarCadastroFornecedorButtonActionPerformed

    private void fornecedorAPesquisarEditarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fornecedorAPesquisarEditarTextFieldKeyReleased
        buscaFornecedorParaEdicao(fornecedorAPesquisarEditarTextField.getText());
        popUpFornecedorAEditar.show(fornecedorAPesquisarEditarTextField, 0, fornecedorAPesquisarEditarTextField.getHeight());
    }//GEN-LAST:event_fornecedorAPesquisarEditarTextFieldKeyReleased

    private void jListaDeFornecedoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaDeFornecedoresValueChanged
       if(cadastroFornecedorPanel.getSelectedIndex()==2){
        if(jListaDeFornecedores.getSelectedIndex()>=0){
        fornecedorAEditar = (Fornecedor)listaDeFornecedores.getElementAt(jListaDeFornecedores.getSelectedIndex());
fornecedorAPesquisarEditarTextField.setText(fornecedorAEditar.toString());
        }
       }
    }//GEN-LAST:event_jListaDeFornecedoresValueChanged

    private void editarFornecedorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFornecedorButtonActionPerformed
     if(fornecedorAEditar != null){
         fornecedorAPesquisarEditarTextField.setText(fornecedorAEditar.toString());
        nomeFornecedorEditarTextField.setText(fornecedorAEditar.getNome());
        fantasiaFornecedorEditarTextField.setText(fornecedorAEditar.getFantasia());
        cnpjFornecedorEditarTextField.setText(fornecedorAEditar.getCnpj());       
        logradouroFornecedorEditarTextField.setText(fornecedorAEditar.getLogradouro());
        numeroFornecedorEditarTextField.setText(fornecedorAEditar.getNumero());
        cepFornecedorEditarTextField.setText(fornecedorAEditar.getCep());
        bairroFornecedorEditarTextField.setText(fornecedorAEditar.getBairro());
        municipioFornecedorEditarTextField.setText(fornecedorAEditar.getMunicipio());
        ufFornecedorEditarTextField.setText(fornecedorAEditar.getUf());
        foneFornecedorEditarTextField.setText(fornecedorAEditar.getFone());
        emailFornecedorEditarTextField.setText(fornecedorAEditar.getEmail());
        tipoPessoaComboBox.setSelectedIndex(tipoDePessoasComboBOx.getIndexOf(TiposDePessoaEnum.valueOf(fornecedorAEditar.getTipoPessoa())));
        statusFornecedorButton.setSelected(fornecedorAEditar.isAtivo());
     }
    }//GEN-LAST:event_editarFornecedorButtonActionPerformed

    private void tipoPessoaCadastroComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPessoaCadastroComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPessoaCadastroComboBoxActionPerformed

    private void filtroTabelaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroTabelaTextFieldKeyReleased
   final TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTabelaDeFornecedores.getModel());
   jTabelaDeFornecedores.setRowSorter(sorter);
        try {
           sorter.setRowFilter(RowFilter.regexFilter(filtroTabelaTextField.getText().toUpperCase()));   
        } catch (Exception e) {
        }
    }//GEN-LAST:event_filtroTabelaTextFieldKeyReleased

    private void cadastroFornecedorPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cadastroFornecedorPanelStateChanged
     if(cadastroFornecedorPanel.getSelectedIndex()==0){
        buscaFornecedoresTabela();  
     }
    }//GEN-LAST:event_cadastroFornecedorPanelStateChanged

    private void exportarParaPlanilhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarParaPlanilhaButtonActionPerformed
            JFileChooser salvarArquivo = new JFileChooser();
     int opcao = salvarArquivo.showSaveDialog(jPanel1);
        if(opcao ==0){
            File caminhoDoArquivo = salvarArquivo.getSelectedFile();
         try {
             Planilha.exportarParaPlanilha(jTabelaDeFornecedores, caminhoDoArquivo.getAbsolutePath());
         } catch (FileNotFoundException ex) {
             Logger.getLogger(PedidoDeCompraView.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
    }//GEN-LAST:event_exportarParaPlanilhaButtonActionPerformed

    private void editarFornecedor(){
        fornecedorAEditar.setNome(nomeFornecedorEditarTextField.getText());
        System.out.println(nomeFornecedorEditarTextField.getText());
        fornecedorAEditar.setFantasia(fantasiaFornecedorEditarTextField.getText());
        fornecedorAEditar.setCep(cnpjFornecedorEditarTextField.getText());
        fornecedorAEditar.setInscricaoEstadual(iEFornecedorEditarTextField.getText());
        fornecedorAEditar.setLogradouro(logradouroFornecedorEditarTextField.getText());
        fornecedorAEditar.setNumero(numeroFornecedorEditarTextField.getText());
        fornecedorAEditar.setCep(cepFornecedorEditarTextField.getText());
        fornecedorAEditar.setBairro(bairroFornecedorEditarTextField.getText());
        fornecedorAEditar.setMunicipio(municipioFornecedorEditarTextField.getText());
        fornecedorAEditar.setUf(ufFornecedorEditarTextField.getText());
        fornecedorAEditar.setFone(foneFornecedorEditarTextField.getText());
        fornecedorAEditar.setEmail(emailFornecedorEditarTextField.getText());
        fornecedorAEditar.setTipoPessoa(TiposDePessoaEnum.valor(tipoDePessoasComboBOx.getSelectedItem().toString()));
        fornecedorAEditar.setAtivo(fornecedorAEditar.estaAtivo(statusFornecedorButton.isSelected()));
    }
    
    
    private boolean validaCamposCadastroFornecedor(){
       StringBuilder erros = new StringBuilder();
       int erro = 0;
        if(!nomeFornecedorCadastrarTextField.getText().isEmpty() &&
           !fantasiaFornecedorCadastrarTextField.getText().isEmpty() &&
            !cnpjFornecedorCadastrarTextField.getText().isEmpty() &&
            !logradouroCadastarFornecedorTextField.getText().isEmpty() &&
             !cepCadastarFornecedorTextField.getText().isEmpty() &&
             !municipioFornecedorFilialTextField.getText().isEmpty() &&
             !ufCadastarFornecedorTextField.getText().isEmpty()){
         if(ufCadastarFornecedorTextField.getText().length() != 2){
             erro++;
             erros.append("UF deve ter dois caracteres \n");
         }   
         if(!cnpjFornecedorCadastrarTextField.getText().isEmpty()
             ){  
          try {
             Long cnpj = Long.valueOf(cnpjFornecedorCadastrarTextField.getText());
             } catch (Exception e) {
            erro++;
           erros.append("CPF/CNPJ com caracteres inválidos \n");
             }
         }
         if(tipoPessoaCadastroComboBox.getSelectedIndex()<0){
          erro++;
           erros.append("Tipo de pessoa não selecionado \n");   
         }
        if(!iEFornecedorCadastrarTextField.getText().isEmpty()){
            try {
                Long inscricaoEstadual =  Long.valueOf(iEFornecedorCadastrarTextField.getText());
            } catch (Exception e) {
             erro++;
           erros.append("Inscrição com caracteres inválidos \n");
            }
        }
        if(erro==0){
            return true;
        }else{
            JOptionPane.showMessageDialog(rootPane, erros);
            return false;
         
        }
        }else{  
         JOptionPane.showMessageDialog(rootPane, "Campos obrigatórios não preenchidos");
        return false;
        }
       
    }
    
    private void buscaFornecedoresTabela(){
        tabelaDeFornecedores.setRowCount(0);
        List<Fornecedor> fornecedores = fornecDao.fornecedores();
        fornecedores.stream().forEach((fornec)->{
         tabelaDeFornecedores.addRow(new Object[]{fornec.getId(), fornec.getNome(), fornec.getFantasia(), fornec.getUf(), fornec.getCnpj(), fornec.getTipoPessoa()});
        });
    }
    
    private void buscaFornecedorParaEdicao(String fornecedor){
       DefaultListModel listaFornec = new DefaultListModel();
        List<Fornecedor> fornecedores = fornecDao.fornecedores();
        fornecedores.stream().forEach((fornec)->{
        if(fornec.toString().contains(fornecedor.toUpperCase())){
         listaFornec.addElement(fornec);
        }
        });
        listaDeFornecedores = listaFornec;
       jListaDeFornecedores.setModel(listaFornec);
    }
    
    private void limpaTela(JPanel panel){
         Component[] componentes = panel.getComponents();
         for(Component c: componentes){
             if(c instanceof JTextField){
                 ((JTextField) c).setText("");
             }
             if(c instanceof JComboBox){
                 ((JComboBox) c).setSelectedIndex(-1);
             }
             fornecedorAEditar = null;
         }
    }
    
    
    
    
    /**
     * @param usuarioLogado
     */
    public static void main(Usuario usuarioLogado) {
       try {
UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeFornecedorView(usuarioLogado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroCadastarFornecedorTextField;
    private javax.swing.JTextField bairroFornecedorEditarTextField;
    private javax.swing.JPanel cadastroFornecedor;
    private javax.swing.JTabbedPane cadastroFornecedorPanel;
    private javax.swing.JTextField cepCadastarFornecedorTextField;
    private javax.swing.JTextField cepFornecedorEditarTextField;
    private javax.swing.JTextField cnpjFornecedorCadastrarTextField;
    private javax.swing.JTextField cnpjFornecedorEditarTextField;
    private javax.swing.JButton editarFornecedorButton;
    private javax.swing.JPanel editarFornecedorPanel;
    private javax.swing.JTextField emailCadastarFornecedorTextField;
    private javax.swing.JTextField emailFornecedorEditarTextField;
    private javax.swing.JButton exportarParaPlanilhaButton;
    private javax.swing.JTextField fantasiaFornecedorCadastrarTextField;
    private javax.swing.JTextField fantasiaFornecedorEditarTextField;
    private javax.swing.JTextField filtroTabelaTextField;
    private javax.swing.JTextField foneCadastarFornecedorTextField;
    private javax.swing.JTextField foneFornecedorEditarTextField;
    private javax.swing.JTextField fornecedorAPesquisarEditarTextField;
    private javax.swing.JTextField iEFornecedorCadastrarTextField;
    private javax.swing.JTextField iEFornecedorEditarTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListaDeFornecedores;
    private javax.swing.JList<String> jListaTiposDePessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneFornec;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTabelaDeFornecedores;
    private javax.swing.JTextField logradouroCadastarFornecedorTextField;
    private javax.swing.JTextField logradouroFornecedorEditarTextField;
    private javax.swing.JTextField municipioFornecedorEditarTextField;
    private javax.swing.JTextField municipioFornecedorFilialTextField;
    private javax.swing.JTextField nomeFornecedorCadastrarTextField;
    private javax.swing.JTextField nomeFornecedorEditarTextField;
    private javax.swing.JTextField numeroCadastarFornecedorTextField;
    private javax.swing.JTextField numeroFornecedorEditarTextField;
    private javax.swing.JPanel panelListaDeFornecedores;
    private javax.swing.JPanel panelListaTiposDepessoa;
    private javax.swing.JPopupMenu popUpFornecedorAEditar;
    private javax.swing.JPopupMenu popUpTipoPessoaFornecedor;
    private javax.swing.JButton salvarCadastroFornecedorButton;
    private javax.swing.JButton salvarCadastroFornecedorlButton;
    private javax.swing.JCheckBox statusFornecedorButton;
    private javax.swing.JComboBox<String> tipoPessoaCadastroComboBox;
    private javax.swing.JComboBox<String> tipoPessoaComboBox;
    private javax.swing.JTextField ufCadastarFornecedorTextField;
    private javax.swing.JTextField ufFornecedorEditarTextField;
    private javax.swing.JLabel usuarioLogadoLabel;
    // End of variables declaration//GEN-END:variables
}
