/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Utils.Planilha;
import com.formdev.flatlaf.FlatLightLaf;
import dbUtils.DepartamentoDao;
import dbUtils.ProdutoDao;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.DepartamentoProduto;
import model.ListaDeProdutos;
import model.Produto;
import model.UnidadeProduto;
import model.Usuario;

/**
 *
 * @author bssil
 */
public class CadastroDeProdutoView extends javax.swing.JFrame {
    DefaultListModel listaDeUnidadesPesquisadas = new DefaultListModel();
    DefaultListModel listaDeDepartamentosPesquisados = new DefaultListModel();
    DefaultListModel listaDeProdutos = new DefaultListModel();
    Produto produtoAEdtiar;
    Usuario usuarioLogado;
    ProdutoDao produtoDao = new ProdutoDao();
    DepartamentoDao departamentoDao = new DepartamentoDao();
    /**
     * Creates new form CadastroDeProdutoView
     * @param usuarioLogado
     */
    public CadastroDeProdutoView(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        usuarioLogadoLabel.setText(usuarioLogado.getNome());
        popUpMenu.add(searchBox);
        popUpCadastroUnidade.add(cadastroUnidadePanel);
        popUpCadastroDepartamento.add(listaDeDepartamentosPopUp);
        popUpProdutos.add(listaDeProdutosPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        searchBox = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListaDeUnidades = new javax.swing.JList<>();
        popUpCadastroUnidade = new javax.swing.JPopupMenu();
        cadastroUnidadePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descricaoUnidadeProdutoTextField = new javax.swing.JTextField();
        cadastrarDescricaoButton = new javax.swing.JButton();
        cadastroDeDepartamento = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cadastroDeDepartamentoDescricao = new javax.swing.JTextField();
        salvarCadastroDeDepartamentoButton = new javax.swing.JButton();
        listaDeDepartamentosPopUp = new javax.swing.JPanel();
        jj = new javax.swing.JScrollPane();
        JListaDeDepartamentos = new javax.swing.JList<>();
        popUpCadastroDepartamento = new javax.swing.JPopupMenu();
        popUpProdutos = new javax.swing.JPopupMenu();
        listaDeProdutosPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JListaDeProdutos = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        usuarioLogadoLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        descriçãoProdutoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        obsProdutoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unidadeProdutoTextField = new javax.swing.JTextField();
        salvarCadastroDeProdutoButton = new javax.swing.JButton();
        abrirCadastroUnidadeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        departamentoProdutoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gtinProdutoCadastroTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cfopCadastroProdutoTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaResultadosProdutos = new javax.swing.JTable();
        filtroProdutosTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        cadastrarNovoDepartamentoButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        editarProdutoDescricaoTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        editarProdutoButton = new javax.swing.JButton();
        unidadeProdutoEditarTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cfopEditarProdutoTextField = new javax.swing.JTextField();
        abrirCadastroUnidadeButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        departamentoProdutoEditarTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        descricaoProdutoEditarTextFiedl = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        obsProdutoEditarTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gtinProdutoEditarTextField = new javax.swing.JTextField();
        salvarProdutoEditadoButton = new javax.swing.JButton();
        desativarProdutoButton = new javax.swing.JCheckBox();

        popUpMenu.setFocusable(false);

        searchBox.setMinimumSize(new java.awt.Dimension(0, 0));
        searchBox.setName(""); // NOI18N

        JListaDeUnidades.setModel(listaDeUnidadesPesquisadas);
        JListaDeUnidades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListaDeUnidades.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JListaDeUnidadesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JListaDeUnidades);

        javax.swing.GroupLayout searchBoxLayout = new javax.swing.GroupLayout(searchBox);
        searchBox.setLayout(searchBoxLayout);
        searchBoxLayout.setHorizontalGroup(
            searchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        searchBoxLayout.setVerticalGroup(
            searchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        jLabel1.setText("DESCRICAO");

        descricaoUnidadeProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cadastrarDescricaoButton.setText("Salvar");
        cadastrarDescricaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDescricaoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroUnidadePanelLayout = new javax.swing.GroupLayout(cadastroUnidadePanel);
        cadastroUnidadePanel.setLayout(cadastroUnidadePanelLayout);
        cadastroUnidadePanelLayout.setHorizontalGroup(
            cadastroUnidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroUnidadePanelLayout.createSequentialGroup()
                .addGroup(cadastroUnidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroUnidadePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(descricaoUnidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroUnidadePanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(cadastrarDescricaoButton)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        cadastroUnidadePanelLayout.setVerticalGroup(
            cadastroUnidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroUnidadePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cadastroUnidadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(descricaoUnidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(cadastrarDescricaoButton)
                .addGap(40, 40, 40))
        );

        cadastroDeDepartamento.setLocationRelativeTo(null);
        cadastroDeDepartamento.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cadastroDeDepartamento.setTitle("Cadastro de departamento");
        cadastroDeDepartamento.setMinimumSize(new java.awt.Dimension(532, 180));
        cadastroDeDepartamento.setResizable(false);
        cadastroDeDepartamento.setSize(new java.awt.Dimension(532, 128));

        jPanel3.setMinimumSize(new java.awt.Dimension(480, 119));
        jPanel3.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descrição");

        cadastroDeDepartamentoDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        salvarCadastroDeDepartamentoButton.setText("Salvar");
        salvarCadastroDeDepartamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCadastroDeDepartamentoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarCadastroDeDepartamentoButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastroDeDepartamentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroDeDepartamentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(salvarCadastroDeDepartamentoButton)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout cadastroDeDepartamentoLayout = new javax.swing.GroupLayout(cadastroDeDepartamento.getContentPane());
        cadastroDeDepartamento.getContentPane().setLayout(cadastroDeDepartamentoLayout);
        cadastroDeDepartamentoLayout.setHorizontalGroup(
            cadastroDeDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroDeDepartamentoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cadastroDeDepartamentoLayout.setVerticalGroup(
            cadastroDeDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroDeDepartamentoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JListaDeDepartamentos.setModel(listaDeDepartamentosPesquisados);
        JListaDeDepartamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListaDeDepartamentos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JListaDeDepartamentosValueChanged(evt);
            }
        });
        jj.setViewportView(JListaDeDepartamentos);

        javax.swing.GroupLayout listaDeDepartamentosPopUpLayout = new javax.swing.GroupLayout(listaDeDepartamentosPopUp);
        listaDeDepartamentosPopUp.setLayout(listaDeDepartamentosPopUpLayout);
        listaDeDepartamentosPopUpLayout.setHorizontalGroup(
            listaDeDepartamentosPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jj, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        listaDeDepartamentosPopUpLayout.setVerticalGroup(
            listaDeDepartamentosPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jj, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        popUpCadastroDepartamento.setFocusable(false);

        popUpProdutos.setFocusable(false);

        JListaDeProdutos.setModel(listaDeProdutos);
        JListaDeProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListaDeProdutos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JListaDeProdutosValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(JListaDeProdutos);

        javax.swing.GroupLayout listaDeProdutosPanelLayout = new javax.swing.GroupLayout(listaDeProdutosPanel);
        listaDeProdutosPanel.setLayout(listaDeProdutosPanelLayout);
        listaDeProdutosPanelLayout.setHorizontalGroup(
            listaDeProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(listaDeProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );
        listaDeProdutosPanelLayout.setVerticalGroup(
            listaDeProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
            .addGroup(listaDeProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de produtos");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        usuarioLogadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        usuarioLogadoLabel.setText("usuario logado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel2.setText("DESCRIÇÃO");

        descriçãoProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setText("OBS");

        obsProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("UNIDADE");

        unidadeProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        unidadeProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadeProdutoTextFieldKeyReleased(evt);
            }
        });

        salvarCadastroDeProdutoButton.setText("Salvar");
        salvarCadastroDeProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCadastroDeProdutoButtonActionPerformed(evt);
            }
        });

        abrirCadastroUnidadeButton.setText("...");
        abrirCadastroUnidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCadastroUnidadeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("DEPARTAMENTO");

        departamentoProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        departamentoProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                departamentoProdutoTextFieldKeyReleased(evt);
            }
        });

        jLabel7.setText("GTIN");

        gtinProdutoCadastroTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gtinProdutoCadastroTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gtinProdutoCadastroTextFieldKeyReleased(evt);
            }
        });

        jLabel8.setText("CFOP");

        cfopCadastroProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cfopCadastroProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cfopCadastroProdutoTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(descriçãoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(obsProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(abrirCadastroUnidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(departamentoProdutoTextField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gtinProdutoCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cfopCadastroProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvarCadastroDeProdutoButton)
                .addGap(113, 113, 113))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descriçãoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(obsProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirCadastroUnidadeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departamentoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gtinProdutoCadastroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cfopCadastroProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvarCadastroDeProdutoButton)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de produto", jPanel2);

        tabelaResultadosProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaResultadosProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabelaResultadosProdutos.setCellSelectionEnabled(true);
        tabelaResultadosProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaResultadosProdutosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaResultadosProdutos);

        filtroProdutosTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                filtroProdutosTextFieldFocusLost(evt);
            }
        });
        filtroProdutosTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroProdutosTextFieldKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sheets.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(filtroProdutosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(filtroProdutosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanel4);

        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabelaResultados.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tabelaResultados);

        cadastrarNovoDepartamentoButton.setText("Novo");
        cadastrarNovoDepartamentoButton.setToolTipText("");
        cadastrarNovoDepartamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoDepartamentoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarNovoDepartamentoButton)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cadastrarNovoDepartamentoButton)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Departamentos", jPanel5);

        jLabel9.setText("Produto");

        editarProdutoDescricaoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editarProdutoDescricaoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editarProdutoDescricaoTextFieldKeyReleased(evt);
            }
        });

        editarProdutoButton.setText("Editar");
        editarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoButtonActionPerformed(evt);
            }
        });

        unidadeProdutoEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        unidadeProdutoEditarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadeProdutoEditarTextFieldKeyReleased(evt);
            }
        });

        jLabel10.setText("CFOP");

        cfopEditarProdutoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        abrirCadastroUnidadeButton1.setText("...");
        abrirCadastroUnidadeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCadastroUnidadeButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("DEPARTAMENTO");

        departamentoProdutoEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        departamentoProdutoEditarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                departamentoProdutoEditarTextFieldKeyReleased(evt);
            }
        });

        jLabel12.setText("DESCRIÇÃO");

        descricaoProdutoEditarTextFiedl.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel13.setText("OBS");

        obsProdutoEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel14.setText("GTIN");

        jLabel15.setText("UNIDADE");

        gtinProdutoEditarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        salvarProdutoEditadoButton.setText("Salvar");
        salvarProdutoEditadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProdutoEditadoButtonActionPerformed(evt);
            }
        });

        desativarProdutoButton.setText("Desativar produto");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarProdutoDescricaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(editarProdutoButton)
                .addGap(27, 27, 27))
            .addComponent(jSeparator1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(desativarProdutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarProdutoEditadoButton)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricaoProdutoEditarTextFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obsProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidadeProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abrirCadastroUnidadeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(departamentoProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gtinProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cfopEditarProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarProdutoDescricaoTextField)
                    .addComponent(editarProdutoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(descricaoProdutoEditarTextFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(obsProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(unidadeProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirCadastroUnidadeButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(departamentoProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(gtinProdutoEditarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cfopEditarProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(salvarProdutoEditadoButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(desativarProdutoButton)))
                .addGap(144, 144, 144))
        );

        jTabbedPane1.addTab("Editar produto", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unidadeProdutoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadeProdutoTextFieldKeyReleased
        buscarUnidadesProduto(unidadeProdutoTextField.getText());
        popUpMenu.show(unidadeProdutoTextField, 0, unidadeProdutoTextField.getHeight());
    }//GEN-LAST:event_unidadeProdutoTextFieldKeyReleased

    private void abrirCadastroUnidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCadastroUnidadeButtonActionPerformed
        popUpCadastroUnidade.show(unidadeProdutoTextField, WIDTH, unidadeProdutoTextField.getHeight());
    }//GEN-LAST:event_abrirCadastroUnidadeButtonActionPerformed

    private void cadastrarDescricaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDescricaoButtonActionPerformed
       String descricaoUnidade = descricaoUnidadeProdutoTextField.getText();
      boolean confirmaCadastroDescricaoProduto = produtoDao.cadastrarUnidadeProduto(descricaoUnidade);
      if(confirmaCadastroDescricaoProduto){
          popUpCadastroUnidade.setVisible(false);
          descricaoUnidadeProdutoTextField.setText("");
      }else{
          JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar unidade do produto");
      }
    }//GEN-LAST:event_cadastrarDescricaoButtonActionPerformed

    private void salvarCadastroDeProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCadastroDeProdutoButtonActionPerformed
        
       if(validaCamposAoCadastrarProduto()){
       UnidadeProduto unidadeProduto = (UnidadeProduto)listaDeUnidadesPesquisadas.getElementAt(JListaDeUnidades.getSelectedIndex());
        DepartamentoProduto dp = (DepartamentoProduto)listaDeDepartamentosPesquisados.getElementAt(JListaDeDepartamentos.getSelectedIndex());
      String produtoCadastrado = produtoDao.cadastrarProduto(
              descriçãoProdutoTextField.getText(), 
              unidadeProduto.getId(), 
              obsProdutoTextField.getText(), 
              dp.getId(), 
              usuarioLogado.getId(),
              cfopCadastroProdutoTextField.getText(),
              gtinProdutoCadastroTextField.getText());
      JOptionPane.showMessageDialog(rootPane, "Produto cadastrado\n Código:" + produtoCadastrado);
       }
    }//GEN-LAST:event_salvarCadastroDeProdutoButtonActionPerformed

    private void JListaDeUnidadesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JListaDeUnidadesValueChanged

        
        if(listaDeUnidadesPesquisadas.getSize()>0){
         if(jTabbedPane1.getSelectedIndex() ==3){
             System.out.println(JListaDeUnidades.getSelectedIndex());
         if(JListaDeUnidades.getSelectedIndex()>=0){
         UnidadeProduto unidadeProduto = (UnidadeProduto)listaDeUnidadesPesquisadas.getElementAt(JListaDeUnidades.getSelectedIndex());
       unidadeProdutoEditarTextField.setText(unidadeProduto.toString());     
         }            
       }
         if(jTabbedPane1.getSelectedIndex() == 0){
         if(listaDeUnidadesPesquisadas.getSize()>=0){
            UnidadeProduto unidadeProduto = (UnidadeProduto)listaDeUnidadesPesquisadas.getElementAt(JListaDeUnidades.getSelectedIndex());
       unidadeProdutoTextField.setText(unidadeProduto.toString());   
           }
         }
         } 
    }//GEN-LAST:event_JListaDeUnidadesValueChanged

    private void departamentoProdutoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoProdutoTextFieldKeyReleased
        buscarDepartamentosProduto(departamentoProdutoTextField.getText());
       popUpCadastroDepartamento.show(departamentoProdutoTextField, 0, departamentoProdutoTextField.getHeight());
    }//GEN-LAST:event_departamentoProdutoTextFieldKeyReleased

    private void cadastrarNovoDepartamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoDepartamentoButtonActionPerformed
        cadastroDeDepartamento.setVisible(true);
    }//GEN-LAST:event_cadastrarNovoDepartamentoButtonActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
       limparTelaEditarProduto();
       listaDeProdutos.setSize(0);
       listaDeUnidadesPesquisadas.setSize(0);
       listaDeDepartamentosPesquisados.setSize(0);
        if(jTabbedPane1.getSelectedIndex() == 2){
            buscarDepartamentosTabela();
        }
        System.out.println(jTabbedPane1.getSelectedIndex());
        if(jTabbedPane1.getSelectedIndex()==1){
            tabelaResultadosProdutos.setRowSorter(null);
            buscarProdutosTabela();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void salvarCadastroDeDepartamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCadastroDeDepartamentoButtonActionPerformed
        if(!cadastroDeDepartamentoDescricao.getText().isEmpty()){
           departamentoDao.inserirNovoDepartamento(cadastroDeDepartamentoDescricao.getText());
           cadastroDeDepartamento.dispose();
           cadastroDeDepartamentoDescricao.setText("");
           buscarDepartamentosTabela();
        }
    }//GEN-LAST:event_salvarCadastroDeDepartamentoButtonActionPerformed

    private void JListaDeDepartamentosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JListaDeDepartamentosValueChanged
        if(jTabbedPane1.getSelectedIndex() == 3 ){
            if(listaDeDepartamentosPesquisados.getSize()>0){
              if(JListaDeDepartamentos.getSelectedIndex()>0){    
       DepartamentoProduto dp = (DepartamentoProduto)listaDeDepartamentosPesquisados.getElementAt(JListaDeDepartamentos.getSelectedIndex());
        departamentoProdutoEditarTextField.setText(dp.toString());    
            }
            }
        }
        if(jTabbedPane1.getSelectedIndex()  == 0){
        if(listaDeDepartamentosPesquisados.getSize()>0){
         DepartamentoProduto dp = (DepartamentoProduto)listaDeDepartamentosPesquisados.getElementAt(JListaDeDepartamentos.getSelectedIndex());
        departamentoProdutoTextField.setText(dp.toString());     
        } 
      
        }
       
    }//GEN-LAST:event_JListaDeDepartamentosValueChanged

    private void filtroProdutosTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroProdutosTextFieldKeyReleased
            final TableRowSorter<TableModel> sorter = new TableRowSorter<>(tabelaResultadosProdutos.getModel());
            tabelaResultadosProdutos.setRowSorter(sorter);
            try {
            sorter.setRowFilter(RowFilter.regexFilter(filtroProdutosTextField.getText().toUpperCase()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_filtroProdutosTextFieldKeyReleased

    private void tabelaResultadosProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaResultadosProdutosMouseClicked
       if(evt.getClickCount() ==2){
       JOptionPane.showMessageDialog(rootPane, "Editar o produto: ");
       }
    }//GEN-LAST:event_tabelaResultadosProdutosMouseClicked

    private void gtinProdutoCadastroTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gtinProdutoCadastroTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gtinProdutoCadastroTextFieldKeyReleased

    private void cfopCadastroProdutoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cfopCadastroProdutoTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cfopCadastroProdutoTextFieldKeyReleased

    private void abrirCadastroUnidadeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCadastroUnidadeButton1ActionPerformed
            popUpCadastroUnidade.show(unidadeProdutoTextField, WIDTH, unidadeProdutoTextField.getHeight());
    }//GEN-LAST:event_abrirCadastroUnidadeButton1ActionPerformed

    private void editarProdutoDescricaoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarProdutoDescricaoTextFieldKeyReleased
       buscarProdutoAEditar(editarProdutoDescricaoTextField.getText());
       popUpProdutos.show(editarProdutoDescricaoTextField, 0, editarProdutoDescricaoTextField.getHeight());
    }//GEN-LAST:event_editarProdutoDescricaoTextFieldKeyReleased

    private void JListaDeProdutosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JListaDeProdutosValueChanged
        if(!JListaDeProdutos.isSelectionEmpty()){
            limparTelaEditarProduto();
           Produto produto = (Produto)listaDeProdutos.getElementAt(JListaDeProdutos.getSelectedIndex());
       editarProdutoDescricaoTextField.setText(produto.toString());  
        }
       
    }//GEN-LAST:event_JListaDeProdutosValueChanged

    private void editarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoButtonActionPerformed
       limparTelaEditarProduto();
        if(JListaDeProdutos.getSelectedIndex() >-1){
      Produto produto = (Produto)listaDeProdutos.getElementAt(JListaDeProdutos.getSelectedIndex());
      produtoAEdtiar = produto;
      editarProdutoDescricaoTextField.setText(produto.toString());
       buscarDepartamentosProduto(".");
       buscarUnidadesProduto(".");
       if(produto.getDepartamentoId() > 0){
         for(int i =0; i<listaDeDepartamentosPesquisados.getSize(); i++){

         DepartamentoProduto dp = (DepartamentoProduto)listaDeDepartamentosPesquisados.getElementAt(i);
         if(produto.getDepartamentoId() == dp.getId()){
           departamentoProdutoEditarTextField.setText(dp.toString());
           JListaDeDepartamentos.setSelectedIndex(i);
         }
         }   
       }
       if(produto.getUnidadeId()>0){
        for(int i=0; i<listaDeUnidadesPesquisadas.getSize(); i++){
            UnidadeProduto und = (UnidadeProduto)listaDeUnidadesPesquisadas.getElementAt(i);
            System.out.println("Index: " + i + " " +und.getDescricao());
            if(produto.getUnidadeId() == und.getId()){
              unidadeProdutoEditarTextField.setText(und.toString()); 
              JListaDeUnidades.setSelectedIndex(i);
            }
            
        }   
       }
       System.out.println(produto.getName() + " " + produto.getCfop() + " " + produto.getGtin());
      descricaoProdutoEditarTextFiedl.setText(produto.getName());
      obsProdutoEditarTextField.setText(produto.getObs());
      gtinProdutoEditarTextField.setText(produto.getGtin());
      cfopEditarProdutoTextField.setText(produto.getCfop());
      if(produto.getDataInativacao().isEmpty()){
      desativarProdutoButton.setText("Ativo");
      desativarProdutoButton.setSelected(true);
      }else{
       desativarProdutoButton.setText("Ativo");
      desativarProdutoButton.setSelected(false);   
      }
       }
    }//GEN-LAST:event_editarProdutoButtonActionPerformed

    private void filtroProdutosTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filtroProdutosTextFieldFocusLost
      filtroProdutosTextField.setText("");
    }//GEN-LAST:event_filtroProdutosTextFieldFocusLost

    private void departamentoProdutoEditarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoProdutoEditarTextFieldKeyReleased
        buscarDepartamentosProduto(departamentoProdutoEditarTextField.getText());
       popUpCadastroDepartamento.show(departamentoProdutoEditarTextField, 0, departamentoProdutoTextField.getHeight());
    }//GEN-LAST:event_departamentoProdutoEditarTextFieldKeyReleased

    private void unidadeProdutoEditarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadeProdutoEditarTextFieldKeyReleased
        buscarUnidadesProduto(unidadeProdutoEditarTextField.getText());
        popUpMenu.show(unidadeProdutoEditarTextField, 0, unidadeProdutoEditarTextField.getHeight());
    }//GEN-LAST:event_unidadeProdutoEditarTextFieldKeyReleased

    private void salvarProdutoEditadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProdutoEditadoButtonActionPerformed
       validarCamposAoEditarProduto();
    }//GEN-LAST:event_salvarProdutoEditadoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFileChooser salvarArquivo = new JFileChooser();
     int opcao = salvarArquivo.showSaveDialog(jPanel1);
        if(opcao ==0){
            File caminhoDoArquivo = salvarArquivo.getSelectedFile();
         try {
             Planilha.exportarParaPlanilha(tabelaResultadosProdutos, caminhoDoArquivo.getAbsolutePath());
         } catch (FileNotFoundException ex) {
             Logger.getLogger(PedidoDeCompraView.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void validarCamposAoEditarProduto(){
        StringBuilder erros = new StringBuilder();
        int qtErros = 0;
        if(produtoAEdtiar != null){
        if(descricaoProdutoEditarTextFiedl.getText().isEmpty()){
         qtErros++;
         erros.append("Descrição do produto não pode estar vazia \n");
        }
       
       if(unidadeProdutoEditarTextField.getText().isEmpty() || JListaDeUnidades.getSelectedIndex()<0){
           qtErros++;
         erros.append("Unidade do produto não foi selecionado da lista\n"); 
        }
        if(departamentoProdutoEditarTextField.getText().isEmpty() || JListaDeDepartamentos.getSelectedIndex()<0){
            qtErros++;
            erros.append("Departamento do produto não foi selecionado da lista\n");
        }
        if(qtErros>0){
            JOptionPane.showMessageDialog(rootPane, erros);
        }else{
        DepartamentoProduto dp = (DepartamentoProduto)listaDeDepartamentosPesquisados.getElementAt(JListaDeDepartamentos.getSelectedIndex());
        UnidadeProduto un = (UnidadeProduto)listaDeUnidadesPesquisadas.getElementAt(JListaDeUnidades.getSelectedIndex());
         Produto p = new Produto();
         p.setAtivo(desativarProdutoButton.isSelected());
         p.setId(produtoAEdtiar.getId());
         p.setName(descricaoProdutoEditarTextFiedl.getText());
         p.setCfop(cfopEditarProdutoTextField.getText());
         p.setDepartamentoId(dp.getId());
         p.setUnidadeId(un.getId());
         p.setGtin(gtinProdutoEditarTextField.getText());
         p.setObs(obsProdutoEditarTextField.getText());
         if(produtoDao.atualizarProduto(p, usuarioLogado)){
         JOptionPane.showMessageDialog(rootPane, "Produto atualizado");
         limparTelaEditarProduto();
         }
        }
        }
    }
    
    private void limparTelaEditarProduto(){
        produtoAEdtiar = null;
        editarProdutoDescricaoTextField.setText("");
        departamentoProdutoEditarTextField.setText("");
        unidadeProdutoEditarTextField.setText("");
        descricaoProdutoEditarTextFiedl.setText("");
      obsProdutoEditarTextField.setText("");
      gtinProdutoEditarTextField.setText("");
      cfopEditarProdutoTextField.setText("");
       desativarProdutoButton.setText("Status");
      desativarProdutoButton.setSelected(false);
    }
    
    private void buscarUnidadesProduto(String unidadePesquisada){
        DefaultListModel unidadesPesquisadas = new DefaultListModel();
        List<UnidadeProduto> unidadesDeProduto = produtoDao.buscarUnidadesProdutos();
        unidadesDeProduto.stream().forEach((unidadeProduto)->{
        if(unidadeProduto.toString().contains(unidadePesquisada.toUpperCase())){
            unidadesPesquisadas.addElement(unidadeProduto);
        }
        else if(unidadePesquisada.substring(0,1).contains(".")){
            unidadesPesquisadas.addElement(unidadeProduto);
        }
        });
        listaDeUnidadesPesquisadas = unidadesPesquisadas;
        JListaDeUnidades.setModel(unidadesPesquisadas);
    }
    
    private void buscarDepartamentosProduto(String departamentoPesquisado){
        DefaultListModel departamentoPesquisados = new DefaultListModel();
        List<DepartamentoProduto> departamentoProdutos= produtoDao.buscarDepartamentosProduto();
        departamentoProdutos.stream().forEach((dp)->{
        if(dp.toString().contains(departamentoPesquisado.toUpperCase())){
            departamentoPesquisados.addElement(dp);
        }
        else if(departamentoPesquisado.substring(0,1).contains(".")){
            departamentoPesquisados.addElement(dp);
        }
        });
        listaDeDepartamentosPesquisados = departamentoPesquisados;
        JListaDeDepartamentos.setModel(departamentoPesquisados);
    }
    
    private void buscarProdutoAEditar(String produtoPesquisado){
        DefaultListModel produtosPesquisados = new DefaultListModel();
        List<Produto> lista = produtoDao.buscarProduto();
        lista.stream().forEach((produto)->{

            if(produto.toString().contains(produtoPesquisado.toUpperCase())){
                produtosPesquisados.addElement(produto);
                System.out.println(produto);
            }
        });
        listaDeProdutos = produtosPesquisados;
       JListaDeProdutos.setModel(produtosPesquisados);
    }
    
    
    private boolean validaCamposAoCadastrarProduto(){
        int contagemErros = 0;
        StringBuilder listaDeErros = new StringBuilder(100);
        System.out.println("Validando campos edição do produto");
        System.out.println("Unidade escolhida: " + JListaDeUnidades.getSelectedIndex());
        System.out.println("Departamento escolhido: " + JListaDeUnidades.getSelectedIndex());
        if(descriçãoProdutoTextField.getText().isEmpty()){
            contagemErros++;
            listaDeErros.append("Descrição do produto está nula\n");
        }
        if(unidadeProdutoTextField.getText().isEmpty()){
            contagemErros++;
            listaDeErros.append("Unidade do produto não selecionada\n");
        }
        if(JListaDeUnidades.getSelectedIndex() <0){
           contagemErros++;
         listaDeErros.append("Unidade do produto não foi selecionado da lista\n"); 
        }
        if(JListaDeDepartamentos.getSelectedIndex()<0){
            contagemErros++;
            listaDeErros.append("Departamento do produto não foi selecionado da lista\n");
        }
        if(contagemErros>0){    
       JOptionPane.showMessageDialog(rootPane, listaDeErros.append("Total de erros: ").append(Integer.toString(contagemErros)).append("\n"));
        return false;
        }
        return true;
    }  
    
    private void buscarDepartamentosTabela(){
        DefaultTableModel listaDeDepartamentos = new DefaultTableModel(){       
    @Override
    public boolean isCellEditable(int row, int column) {
              return false; 
    }
    };
        List<DepartamentoProduto> lista = new ArrayList<>();
        lista = departamentoDao.buscarDepartamentosProduto();
        listaDeDepartamentos.addColumn("ID");
        listaDeDepartamentos.addColumn("DESCRICAO");
       
        tabelaResultados.setModel(listaDeDepartamentos);
        lista.stream().forEach((departamento)->{
            listaDeDepartamentos.addRow(new Object[]{departamento.getId(), departamento.getDescricao()});
        });
          
    }
    
    
    private void buscarProdutosTabela(){
        DefaultTableModel listaDeProdutos = new DefaultTableModel(){       
    @Override
    public boolean isCellEditable(int row, int column) {
              return false; 
    }
    };
         List<ListaDeProdutos> lista = new ArrayList<>();
        lista = produtoDao.buscarProdutos();
        listaDeProdutos.addColumn("ID");
        listaDeProdutos.addColumn("DESCRICAO");
        listaDeProdutos.addColumn("DEPARTAMENTO");
        listaDeProdutos.addColumn("OBS");
        listaDeProdutos.addColumn("ATIVO");
    
       
        tabelaResultadosProdutos.setModel(listaDeProdutos);      
        lista.stream().forEach((produto)->{
            System.out.println(produto.getNome());
            listaDeProdutos.addRow(new Object[]{produto.getProduto_id(), produto.getNome(), produto.getDepartamento(), produto.getObs(), produto.getInativo()});
          
        });
        tabelaResultadosProdutos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
    @Override
    public Component getTableCellRendererComponent(JTable table,
            Object value, boolean isSelected, boolean hasFocus, int row, int col) {

        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

        String status = (String)table.getModel().getValueAt(row, 4);
        if ("N".equals(status)) {
            setBackground(Color.GRAY);
            setForeground(Color.WHITE);
        } else {
            setBackground(table.getBackground());
            setForeground(table.getForeground());
        }       
        return this;
    }   
});
    }
    
    
    /**
     * @param usuarioLogado
     * @param args the command line arguments
     */
    public static void main(Usuario usuarioLogado) {
          try {
UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeProdutoView(usuarioLogado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListaDeDepartamentos;
    private javax.swing.JList<String> JListaDeProdutos;
    private javax.swing.JList<String> JListaDeUnidades;
    private javax.swing.JButton abrirCadastroUnidadeButton;
    private javax.swing.JButton abrirCadastroUnidadeButton1;
    private javax.swing.JButton cadastrarDescricaoButton;
    private javax.swing.JButton cadastrarNovoDepartamentoButton;
    private javax.swing.JFrame cadastroDeDepartamento;
    private javax.swing.JTextField cadastroDeDepartamentoDescricao;
    private javax.swing.JPanel cadastroUnidadePanel;
    private javax.swing.JTextField cfopCadastroProdutoTextField;
    private javax.swing.JTextField cfopEditarProdutoTextField;
    private javax.swing.JTextField departamentoProdutoEditarTextField;
    private javax.swing.JTextField departamentoProdutoTextField;
    private javax.swing.JCheckBox desativarProdutoButton;
    private javax.swing.JTextField descricaoProdutoEditarTextFiedl;
    private javax.swing.JTextField descricaoUnidadeProdutoTextField;
    private javax.swing.JTextField descriçãoProdutoTextField;
    private javax.swing.JButton editarProdutoButton;
    private javax.swing.JTextField editarProdutoDescricaoTextField;
    private javax.swing.JTextField filtroProdutosTextField;
    private javax.swing.JTextField gtinProdutoCadastroTextField;
    private javax.swing.JTextField gtinProdutoEditarTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane jj;
    private javax.swing.JPanel listaDeDepartamentosPopUp;
    private javax.swing.JPanel listaDeProdutosPanel;
    private javax.swing.JTextField obsProdutoEditarTextField;
    private javax.swing.JTextField obsProdutoTextField;
    private javax.swing.JPopupMenu popUpCadastroDepartamento;
    private javax.swing.JPopupMenu popUpCadastroUnidade;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JPopupMenu popUpProdutos;
    private javax.swing.JButton salvarCadastroDeDepartamentoButton;
    private javax.swing.JButton salvarCadastroDeProdutoButton;
    private javax.swing.JButton salvarProdutoEditadoButton;
    private javax.swing.JPanel searchBox;
    private javax.swing.JTable tabelaResultados;
    private javax.swing.JTable tabelaResultadosProdutos;
    private javax.swing.JTextField unidadeProdutoEditarTextField;
    private javax.swing.JTextField unidadeProdutoTextField;
    private javax.swing.JLabel usuarioLogadoLabel;
    // End of variables declaration//GEN-END:variables
}
