/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import dbUtils.FilialDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Filial;
import model.Usuario;

/**
 *
 * @author bssil
 */
public class CadastroFilialView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFilialView
     * @param usuarioLogado
     */
    public CadastroFilialView(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        usuarioLogadoLabel.setText(this.usuarioLogado.getNome());
        popUpFilialPesquisada.add(filialPesquisadaPanel);
    }

    Usuario usuarioLogado;
    FilialDao filialDao = new FilialDao();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpFilialPesquisada = new javax.swing.JPopupMenu();
        filialPesquisadaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaDeFiliaisPesquisadas = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filialASerPesquisadaTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        nomeFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fantasiaFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cnpjFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        logradouroFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        numeroFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cepFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        bairroFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        municipioFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ufFIlialPesquisadaTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        foneFilialPesquisadaTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        emailFilialPesquisadaTextField = new javax.swing.JTextField();
        cadastrarFilialPanel = new javax.swing.JPanel();
        nomeFilialCadastrarTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fantasiaFilialCadastrarTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnpjCadastrarTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        logradouroCadastarFilialTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numeroCadastarFilialTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cepCadastarFilialTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bairroCadastarFilialTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        municipioCadastarFilialTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ufCadastarFilialTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        foneCadastarFilialTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailCadastarFilialTextField = new javax.swing.JTextField();
        salvarCadastroFilialButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        usuarioLogadoLabel = new javax.swing.JLabel();

        popUpFilialPesquisada.setFocusable(false);

        jListaDeFiliaisPesquisadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaDeFiliaisPesquisadasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaDeFiliaisPesquisadas);

        javax.swing.GroupLayout filialPesquisadaPanelLayout = new javax.swing.GroupLayout(filialPesquisadaPanel);
        filialPesquisadaPanel.setLayout(filialPesquisadaPanelLayout);
        filialPesquisadaPanelLayout.setHorizontalGroup(
            filialPesquisadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        filialPesquisadaPanelLayout.setVerticalGroup(
            filialPesquisadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setText("FILIAL");

        filialASerPesquisadaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filialASerPesquisadaTextFieldKeyReleased(evt);
            }
        });

        jLabel13.setText("NOME");

        jLabel14.setText("FANTASIA");

        jLabel15.setText("CNPJ");

        cnpjFilialPesquisadaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel16.setText("LOGRADOURO");

        jLabel17.setText("NUMERO");

        jLabel18.setText("CEP");

        jLabel19.setText("BAIRRO");

        jLabel20.setText("MUNICIPIO");

        jLabel21.setText("UF");

        jLabel22.setText("FONE");

        jLabel23.setText("EMAIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filialASerPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logradouroFilialPesquisadaTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnpjFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fantasiaFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cepFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bairroFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufFIlialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foneFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(filialASerPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantasiaFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(logradouroFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(numeroFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cepFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(bairroFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(municipioFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(ufFIlialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(foneFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(emailFilialPesquisadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filiais", jPanel1);

        jLabel1.setText("NOME");

        jLabel2.setText("FANTASIA");

        jLabel3.setText("CNPJ");

        cnpjCadastrarTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("LOGRADOURO");

        jLabel5.setText("NUMERO");

        jLabel6.setText("CEP");

        jLabel7.setText("BAIRRO");

        jLabel8.setText("MUNICIPIO");

        jLabel9.setText("UF");

        jLabel10.setText("FONE");

        jLabel11.setText("EMAIL");

        salvarCadastroFilialButton.setText("Salvar");
        salvarCadastroFilialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCadastroFilialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastrarFilialPanelLayout = new javax.swing.GroupLayout(cadastrarFilialPanel);
        cadastrarFilialPanel.setLayout(cadastrarFilialPanelLayout);
        cadastrarFilialPanelLayout.setHorizontalGroup(
            cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                        .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnpjCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fantasiaFilialCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeFilialCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cepCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bairroCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logradouroCadastarFilialTextField))
                            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(salvarCadastroFilialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                                        .addComponent(foneCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        cadastrarFilialPanelLayout.setVerticalGroup(
            cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarFilialPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeFilialCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantasiaFilialCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjCadastrarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(logradouroCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cepCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(bairroCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(municipioCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ufCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastrarFilialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(foneCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(emailCadastarFilialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(salvarCadastroFilialButton)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Cadastrar filial", cadastrarFilialPanel);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setForeground(new java.awt.Color(0, 153, 204));

        usuarioLogadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        usuarioLogadoLabel.setText("usuarioLogado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioLogadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarCadastroFilialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCadastroFilialButtonActionPerformed
      if(validarCamposAoCadastarFilial()){
      Filial filial = new Filial();
      filial.setNome(nomeFilialCadastrarTextField.getText());
      filial.setFantasia(fantasiaFilialCadastrarTextField.getText());
      filial.setBairro(bairroCadastarFilialTextField.getText());
      filial.setMunicipio(municipioCadastarFilialTextField.getText());
      filial.setCep(cepCadastarFilialTextField.getText());
      filial.setCnpj(cnpjCadastrarTextField.getText());
      filial.setNumero(numeroCadastarFilialTextField.getText());
      filial.setEmail(emailCadastarFilialTextField.getText());
      filial.setFone(foneCadastarFilialTextField.getText());
      filial.setLogradouro(logradouroCadastarFilialTextField.getText());
      filial.setUf(ufCadastarFilialTextField.getText());
      FilialDao dao = new FilialDao();
      if(dao.cadastrarFilial(filial)){
          JOptionPane.showMessageDialog(rootPane, "Filial cadastrada");
      }
      }
    }//GEN-LAST:event_salvarCadastroFilialButtonActionPerformed

    private void filialASerPesquisadaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filialASerPesquisadaTextFieldKeyReleased
        buscaFilialASerPesquisada(filialASerPesquisadaTextField.getText());
        popUpFilialPesquisada.show(filialASerPesquisadaTextField, 0, filialASerPesquisadaTextField.getHeight());
    }//GEN-LAST:event_filialASerPesquisadaTextFieldKeyReleased

    private void jListaDeFiliaisPesquisadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaDeFiliaisPesquisadasValueChanged
    if(jTabbedPane1.getSelectedIndex() == 0){
    DefaultListModel filiaisPesquisadas = new DefaultListModel(); 
    filiaisPesquisadas = (DefaultListModel) jListaDeFiliaisPesquisadas.getModel();
  
    if(jListaDeFiliaisPesquisadas.getSelectedIndex()>=0){
    Filial filial = (Filial)filiaisPesquisadas.getElementAt(jListaDeFiliaisPesquisadas.getSelectedIndex());   
    filialASerPesquisadaTextField.setText(filial.toString());
    popUpFilialPesquisada.setVisible(false);
    nomeFilialPesquisadaTextField.setText(filial.getNome());
    fantasiaFilialPesquisadaTextField.setText(filial.getFantasia());
    cnpjFilialPesquisadaTextField.setText(filial.getCnpj());
    logradouroFilialPesquisadaTextField.setText(filial.getLogradouro());
    numeroFilialPesquisadaTextField.setText(filial.getNumero());
    cepFilialPesquisadaTextField.setText(filial.getCep());
    bairroFilialPesquisadaTextField.setText(filial.getBairro());
    municipioFilialPesquisadaTextField.setText(filial.getMunicipio());
    ufFIlialPesquisadaTextField.setText(filial.getUf());
    foneFilialPesquisadaTextField.setText(filial.getFone());
    emailFilialPesquisadaTextField.setText(filial.getEmail());
    }
    }
    }//GEN-LAST:event_jListaDeFiliaisPesquisadasValueChanged

    private boolean validarCamposAoCadastarFilial(){
        StringBuilder erros = new StringBuilder();
        int erro = 0;
        if(nomeFilialCadastrarTextField.getText().isEmpty()){
        erro++;
        erros.append("Nome da filial não informado \n");
        }
        if(fantasiaFilialCadastrarTextField.getText().isEmpty()){
        erro++;
        erros.append("Fantasia da filial não informada \n");
        }
        if(cnpjCadastrarTextField.getText().isEmpty()){
        erro++;
        erros.append("CNPJ não informado"); 
        }
        if(!cnpjCadastrarTextField.getText().isEmpty()){
              try {
          Long cnpj = Long.valueOf(cnpjCadastrarTextField.getText());
            } catch (Exception e) {
                erro++;
                erros.append("CNPJ contém caracteres inválidos \n");
                System.out.println(e);
            }
              if(cnpjCadastrarTextField.getText().length() !=14){
                   erro++;
                erros.append("CNPJ não contém 14 digítos \n");  
              }
        }
        if(logradouroCadastarFilialTextField.getText().isEmpty()){
        erro++;
        erros.append("Logradouro não informado \n");
        }
        if(numeroCadastarFilialTextField.getText().isEmpty()){
        erro++;
        erros.append("Numero não informado \n");    
        }
        if(cepCadastarFilialTextField.getText().isEmpty()){
        erro++;
        erros.append("CEP não informado \n");     
        }
        if(!cepCadastarFilialTextField.getText().isEmpty()){
         try {
          int cep = Integer.parseInt(cepCadastarFilialTextField.getText());
            } catch (Exception e) {
                erro++;
                erros.append("CEP contém caracteres inválidos \n");
                System.out.println(e);
            }
              if(cepCadastarFilialTextField.getText().length() !=8){
                   erro++;
                erros.append("CEP não contém 8 digítos \n");  
              }    
        }
        if(bairroCadastarFilialTextField.getText().isEmpty()){
        erro++;
        erros.append("Bairro não informado \n");    
        }
        if(municipioCadastarFilialTextField.getText().isEmpty()){
         erro++;
        erros.append("Municipio não informado \n");  
        }
        if(ufCadastarFilialTextField.getText().isEmpty()){
            erro++;
        erros.append("Uf não informado \n");     
        }
        if(!ufCadastarFilialTextField.getText().isEmpty()){
        if(ufCadastarFilialTextField.getText().length() != 2){
         erro++;
         erros.append("UF deve conter apenas dois caracteres \n");
        }
        }
        if(erro>0){
            JOptionPane.showMessageDialog(rootPane, erros);
            return false;
        }
        if(erro ==0){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void buscaFilialASerPesquisada(String filialPesquisada){
      DefaultListModel filiaisPesquisadas = new DefaultListModel(); 
      List<Filial> filiais = filialDao.buscarFilials();
      filiais.stream().forEach((filial)->{
        if(filial.toString().contains(filialPesquisada.toUpperCase())){
                filiaisPesquisadas.addElement(filial);
                System.out.println(filial);
            }   
          else if(filialPesquisada.substring(0,1).contains(".")){
            filiaisPesquisadas.addElement(filial);
        }
      });
      jListaDeFiliaisPesquisadas.setModel(filiaisPesquisadas);
    }
    
    
    
    
    
    
    /**
     * @param usuario
     * @param args the command line arguments
     */
    public static void main(Usuario usuario) {
     try {
UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilialView(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroCadastarFilialTextField;
    private javax.swing.JTextField bairroFilialPesquisadaTextField;
    private javax.swing.JPanel cadastrarFilialPanel;
    private javax.swing.JTextField cepCadastarFilialTextField;
    private javax.swing.JTextField cepFilialPesquisadaTextField;
    private javax.swing.JTextField cnpjCadastrarTextField;
    private javax.swing.JTextField cnpjFilialPesquisadaTextField;
    private javax.swing.JTextField emailCadastarFilialTextField;
    private javax.swing.JTextField emailFilialPesquisadaTextField;
    private javax.swing.JTextField fantasiaFilialCadastrarTextField;
    private javax.swing.JTextField fantasiaFilialPesquisadaTextField;
    private javax.swing.JTextField filialASerPesquisadaTextField;
    private javax.swing.JPanel filialPesquisadaPanel;
    private javax.swing.JTextField foneCadastarFilialTextField;
    private javax.swing.JTextField foneFilialPesquisadaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListaDeFiliaisPesquisadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField logradouroCadastarFilialTextField;
    private javax.swing.JTextField logradouroFilialPesquisadaTextField;
    private javax.swing.JTextField municipioCadastarFilialTextField;
    private javax.swing.JTextField municipioFilialPesquisadaTextField;
    private javax.swing.JTextField nomeFilialCadastrarTextField;
    private javax.swing.JTextField nomeFilialPesquisadaTextField;
    private javax.swing.JTextField numeroCadastarFilialTextField;
    private javax.swing.JTextField numeroFilialPesquisadaTextField;
    private javax.swing.JPopupMenu popUpFilialPesquisada;
    private javax.swing.JButton salvarCadastroFilialButton;
    private javax.swing.JTextField ufCadastarFilialTextField;
    private javax.swing.JTextField ufFIlialPesquisadaTextField;
    private javax.swing.JLabel usuarioLogadoLabel;
    // End of variables declaration//GEN-END:variables
}
