/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import Enums.ConfiguracaoBancoDeDadosEnum;
import Utils.arquivoUtils;
import com.formdev.flatlaf.FlatLightLaf;
import dbUtils.DbUtils;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.UIManager;
import model.Usuario;


/**
 *
 * @author bssil
 */
public class LoginPage extends javax.swing.JFrame {
     DbUtils dbUtils;
     
    /** Creates new form Login */
    public LoginPage() {
        initComponents();
   
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configuracaoBancoDeDadosjFrame = new javax.swing.JFrame();
        configBancoDeDadosPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        urlBancoDeDadosTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usuarioBancoDeDadosTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        senhaBancoDeDadosTextField = new javax.swing.JTextField();
        salvarConfigBancoDeDados = new javax.swing.JButton();
        testarConfigBancoDeDadosButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        driverBancoDeDadosTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        senhaTextField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        configButton = new javax.swing.JButton();

        configuracaoBancoDeDadosjFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configuracaoBancoDeDadosjFrame.setMaximumSize(new java.awt.Dimension(599, 265));
        configuracaoBancoDeDadosjFrame.setMinimumSize(new java.awt.Dimension(599, 265));
        configuracaoBancoDeDadosjFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                configuracaoBancoDeDadosjFrameWindowClosed(evt);
            }
        });

        configBancoDeDadosPanel.setMaximumSize(new java.awt.Dimension(599, 265));
        configBancoDeDadosPanel.setMinimumSize(new java.awt.Dimension(599, 265));
        configBancoDeDadosPanel.setPreferredSize(new java.awt.Dimension(599, 300));

        jLabel3.setText("URL BANCO DE DADOS");

        urlBancoDeDadosTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        urlBancoDeDadosTextField.setToolTipText("");

        jLabel4.setText("USUARIO");

        usuarioBancoDeDadosTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usuarioBancoDeDadosTextField.setToolTipText("");

        jLabel5.setText("SENHA");

        senhaBancoDeDadosTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        senhaBancoDeDadosTextField.setToolTipText("");

        salvarConfigBancoDeDados.setText("Salvar");
        salvarConfigBancoDeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarConfigBancoDeDadosActionPerformed(evt);
            }
        });

        testarConfigBancoDeDadosButton.setText("Testar");
        testarConfigBancoDeDadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testarConfigBancoDeDadosButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("DRIVER");

        javax.swing.GroupLayout configBancoDeDadosPanelLayout = new javax.swing.GroupLayout(configBancoDeDadosPanel);
        configBancoDeDadosPanel.setLayout(configBancoDeDadosPanelLayout);
        configBancoDeDadosPanelLayout.setHorizontalGroup(
            configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                        .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuarioBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(senhaBancoDeDadosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                    .addComponent(driverBancoDeDadosTextField))))
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configBancoDeDadosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(testarConfigBancoDeDadosButton)
                        .addGap(33, 33, 33)
                        .addComponent(salvarConfigBancoDeDados)
                        .addGap(61, 61, 61))))
        );
        configBancoDeDadosPanelLayout.setVerticalGroup(
            configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configBancoDeDadosPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urlBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usuarioBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(senhaBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(driverBancoDeDadosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(configBancoDeDadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testarConfigBancoDeDadosButton)
                    .addComponent(salvarConfigBancoDeDados))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout configuracaoBancoDeDadosjFrameLayout = new javax.swing.GroupLayout(configuracaoBancoDeDadosjFrame.getContentPane());
        configuracaoBancoDeDadosjFrame.getContentPane().setLayout(configuracaoBancoDeDadosjFrameLayout);
        configuracaoBancoDeDadosjFrameLayout.setHorizontalGroup(
            configuracaoBancoDeDadosjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configBancoDeDadosPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        configuracaoBancoDeDadosjFrameLayout.setVerticalGroup(
            configuracaoBancoDeDadosjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configuracaoBancoDeDadosjFrameLayout.createSequentialGroup()
                .addComponent(configBancoDeDadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de compras");
        setResizable(false);

        loginTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("LOGIN:");

        jLabel2.setText("SENHA:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        configButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gear.png"))); // NOI18N
        configButton.setToolTipText("");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginButton)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginTextField)
                            .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(configButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(loginButton)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(configButton)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed

    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if(arquivoUtils.checaSeOArquivoExiste()){
        Properties props = arquivoUtils.lerArquivoDeConfiguracao();
     if(DbUtils.testeDeConexao(props)){
       String usuario = loginTextField.getText();
       String senha = senhaTextField.getText();
        DbUtils dbUtils = new DbUtils(props);
       if(dbUtils.logar(usuario, senha) != null){
        //String[] args = null;
        Usuario usuarioLogado = dbUtils.logar(usuario, senha);
        HomePageView.main(usuarioLogado);
         this.dispose();
    }else{
        JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválidos");
    }
     }   
    }
   

    
    }//GEN-LAST:event_loginButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed

        preencheCamposConfiguracaoBancoDeDados();
        configuracaoBancoDeDadosjFrame.setVisible(true);
    
    }//GEN-LAST:event_configButtonActionPerformed

    private void salvarConfigBancoDeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarConfigBancoDeDadosActionPerformed
     
     if(validaCamposTesteBancoDeDados()){
        try {//jdbc:mariadb://{host}[:{port}]/[{database}]
        if(arquivoUtils.salvarArquivoDeConfiguracao(propriedadesBancoDeDados())){
            JOptionPane.showMessageDialog(null, "Configurações salvas");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
     }
       
    }//GEN-LAST:event_salvarConfigBancoDeDadosActionPerformed

    private void testarConfigBancoDeDadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testarConfigBancoDeDadosButtonActionPerformed
        if(validaCamposTesteBancoDeDados()){
         testarConfiguracaoBancoDeDados();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        }
    }//GEN-LAST:event_testarConfigBancoDeDadosButtonActionPerformed

    private void configuracaoBancoDeDadosjFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_configuracaoBancoDeDadosjFrameWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_configuracaoBancoDeDadosjFrameWindowClosed

    private void preencheCamposConfiguracaoBancoDeDados(){
        if(arquivoUtils.checaSeOArquivoExiste()){
          Properties props = arquivoUtils.lerArquivoDeConfiguracao();
         urlBancoDeDadosTextField.setText(props.getProperty(ConfiguracaoBancoDeDadosEnum.JDBC_URL.getValor())); 
         usuarioBancoDeDadosTextField.setText(props.getProperty(ConfiguracaoBancoDeDadosEnum.JDBC_USERNAME.getValor()));
         senhaBancoDeDadosTextField.setText(props.getProperty(ConfiguracaoBancoDeDadosEnum.JDBC_PASSWORD.getValor()));
         driverBancoDeDadosTextField.setText(props.getProperty(ConfiguracaoBancoDeDadosEnum.getJDBC_DRIVER().getValor()));
        }
    }
    
    private void testarConfiguracaoBancoDeDados(){
       if(arquivoUtils.checaSeOArquivoExiste()){
         Properties props = arquivoUtils.lerArquivoDeConfiguracao();
         if(DbUtils.testeDeConexao(props)){
         JOptionPane.showMessageDialog(null, "Conexão bem sucedida");
         }else{
              JOptionPane.showMessageDialog(null, "Falha ao conectar ao banco de dados");
         }
       } 
       else{
          if(validaCamposTesteBancoDeDados()){
          Properties props = propriedadesBancoDeDados();
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_DRIVER.getValor(), driverBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_USERNAME.getValor(),usuarioBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_PASSWORD.getValor(), senhaBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_URL.getValor(), urlBancoDeDadosTextField.getText());
          if(DbUtils.testeDeConexao(props)){
            JOptionPane.showMessageDialog(null, "Conexão bem sucedida");   
          }else{
               JOptionPane.showMessageDialog(null, "Falha ao conectar ao banco de dados");
          }
          
          } 
       }
    }
    
    
    private boolean validaCamposTesteBancoDeDados(){
        return  !urlBancoDeDadosTextField.getText().isEmpty() &&
                !usuarioBancoDeDadosTextField.getText().isEmpty() &&
                !senhaBancoDeDadosTextField.getText().isEmpty() &&
                !driverBancoDeDadosTextField.getText().isEmpty();
    }
    
    
    private Properties propriedadesBancoDeDados(){
        Properties props = new Properties();
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_DRIVER.getValor(), driverBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_USERNAME.getValor(),usuarioBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_PASSWORD.getValor(), senhaBancoDeDadosTextField.getText());
          props.setProperty(ConfiguracaoBancoDeDadosEnum.JDBC_URL.getValor(), urlBancoDeDadosTextField.getText());
          return props;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configBancoDeDadosPanel;
    private javax.swing.JButton configButton;
    private javax.swing.JFrame configuracaoBancoDeDadosjFrame;
    private javax.swing.JTextField driverBancoDeDadosTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JButton salvarConfigBancoDeDados;
    private javax.swing.JTextField senhaBancoDeDadosTextField;
    private javax.swing.JPasswordField senhaTextField;
    private javax.swing.JButton testarConfigBancoDeDadosButton;
    private javax.swing.JTextField urlBancoDeDadosTextField;
    private javax.swing.JTextField usuarioBancoDeDadosTextField;
    // End of variables declaration//GEN-END:variables

}
